name: Build Arch images

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install archiso
        run: pacman -Syyu --noconfirm && pacman -S archiso grub skopeo --noconfirm


      - name: Build bootstrap tarball
        run: mkarchiso -v -r -w /tmp/archiso-tmp -o ../output/ ./archsource/

      - name: Import and push to ghcr.io
        run: |
          skopeo copy \
            docker-archive: ./output/archlinux-optativa-bootstrap-*.xz \
            docker://ghcr.io/${{ github.repository }}:latest \
            --dest-creds ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}

      - name: Tag with commit SHA
        run: |
          skopeo copy \
            docker://ghcr.io/${{ github.repository }}:latest \
            docker://ghcr.io/${{ github.repository }}:${{ github.sha }} \
            --dest-creds ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
